version: "3.8"
services:
  webapp:
    image: watermodelling/hydrus-modflow-synergy-engine:water-modelling-standalone
    ports:
      - "5000:5000"
    volumes:
      - ./water_modelling/workspace:/water_modelling/workspace
      - /var/run/docker.sock:/var/run/docker.sock