apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      volumes:
      - name: nfs-vol
        persistentVolumeClaim:
          claimName: non-exisiting-pvc
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
        volumeMounts:
        - name: nfs-vol
          mountPath: /test
      restartPolicy: Never
  backoffLimit: 4