apiVersion: v1
kind: Service
metadata:
  name: water-service
spec:
  type: NodePort
  selector:
    app: water-modelling-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30036