apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-nfs-server-provisioner-0
spec:
  storageClassName: "standard"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/observer46/inzynierka/test_volume
  claimRef:
    namespace: kube-system
    name: data-nfs-server-provisioner-0