apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: web-app-role
rules:
  - apiGroups: [""]
    resources:
      - pods
      - jobs
    verbs:
      - create
      - get
      - list
      - delete