apiVersion: v1
kind: Pod
metadata:
   name: modflow-2005
spec:
   containers:
   - image: mjstealey/docker-modflow
     name: kicajki
     volumeMounts:
     - mountPath: "/workspace"
       name: my-path
     args: ["mf2005", "tutorial_2.nam"]
     securityContext:
       privileged: true
   volumes:
   - name: my-path
     hostPath:
       path: /run/desktop/mnt/host/d/Playground/Modflow
       type: DirectoryOrCreate
   restartPolicy: Never
